### PR TITLE
Avoid recurring function calls in loops.

### PR DESCRIPTION
**Pull request by WouterSioen**
In debug mode on a big template, this change can improve your page speed with more then 250ms.

### CODE REVIEW

**Comment by dubgeiser** [comment]
Is there a reason the debug setting isn't made an instance variable?

**Comment by WouterSioen** [comment]
nope, not really. This could be an even better improvement.

It could be possible to change the Spoon $debug variable between the construction of the SpoonTemplateCompiler object and the calls to the parse method, but we could call `Spoon::getDebug()` once in the beginning of the parse method and put it in an instance variable there.

**Comment by dubgeiser** [comment]
I don't think I would actually bother with that, since parse() already caches the output (see $this->parsed).
I'd set it via ctor injection, in this case as an optional ctor argument and set it via ```Spoon::getDebug()``` if not given, allowing you to set it differently when necessary (example in a test suite).
(All personal opinion, mind you ;-) )

**Comment by WouterSioen** [comment]
This seems more logical. I've updated the code to handle your feedback.

**Comment by WouterSioen** [comment]
I handled  the feedback

**Pull request merged**
