### PR TITLE
Library cleanup

### PR DESCRIPTION
**Pull request by carakas**
Clean up some things we no longer need in fork

### CODE REVIEW

**Comment by jonasdekeukelaere** [comment]
Why remove it from this library?

**Comment by carakas** [comment]
so people can't use it anymore

**Comment by jonasdekeukelaere** [comment]
Not sure if that a solution. People might want to use this, for some reason.

**Comment by carakas** [comment]
But they shouldn't, this isn't just Spoon Library, this is a fork of the original Spoon Library tailored to fork, therefore if we move away with things in fork we can and should remove it here

**Comment by jeroendesloovere** [comment]
👍

**Comment by tijsverkoyen** [comment]
👍

**Pull request merged**
