### PR TITLE
Fixes `null` values from being converted to empty string in SpoonDataGrid columnFunctions

### PR DESCRIPTION
**Pull request by jeroendesloovere**
## Problem

Full [problem description](https://github.com/forkcms/forkcms/issues/2052).

Summary:
When giving a null to a SpoonDataGrid columnFunction, this will be converted to a string. But that isn't wanted behavior since we are using PHP 7.1 type casting.

## Solution

The json_decode/encode is 3x faster then str_replace and ALSO fixes the problem. 
http://php.net/manual/en/function.str-replace.php

### CODE REVIEW

**Comment by carakas** [comment]
@jeroendesloovere is this a BC break?

**Comment by jeroendesloovere** [comment]
Screenshots to show the result of this fix:
Before the fix:
schermafbeelding 2017-06-08 om 09 50 01

After the fix:
schermafbeelding 2017-06-08 om 09 49 55

**Comment by jeroendesloovere** [comment]
I've clicked through some modules and didn't saw strange behavior.

**Comment by jeroendesloovere** [comment]
@carakas can you please look into this one, so I can update https://github.com/forkcms/forkcms/pull/2055 to get that merged in fork cms 5 (and then the thumbnails in MediaItemIndex will work again)

**Comment by carakas** [comment]
@jeroendesloovere this is still a BC break and we won't release major version with one change knowing that there is more that needs to change here for fork 5 so you will have to wait a bit

**Comment by jeroendesloovere** [comment]
Why is this a BC break?

**Comment by carakas** [comment]
because it now returns an empty string and after this is would return null so like I said in my previous comment if someone is checking on empty string and not null this will break their code

**Pull request merged**
