### PR TITLE
Make sure no notices are thrown.

### PR DESCRIPTION
**Pull request by WouterSioen**
This fixes https://github.com/forkcms/library/commit/9d21f2ae912efeb5b7ab6f2702d407c9894e4707#commitcomment-10463745

### CODE REVIEW

**Comment by WouterSioen** [comment]
@bart-webleads @vytenizs  what do you think? Should fix the issue.

**Comment by vytenizs** [comment]
I bet locale will never be null, it will be an empty array.

**Comment by WouterSioen** [comment]
I define it myself as null with `protected static $locale = null`

**Comment by vytenizs** [comment]
sorry. I see. Cant we just add self::locale[$language] and check if that locale was loaded or not. And if not load that locale for that language into static variable. If it is loaded just use it.

**Comment by bart-webleads** [comment]
May be add an extra "$locale = array();" to be safe and keep the code inspector happy...

```
		if (self::$locale === null)
		{
			$locale = array();
			require_once 'spoon/locale/data/' . $language . '.php';
			self::$locale = $locale;
		}
```

**Comment by vytenizs** [comment]
for example:
$locale  = isset(self::$locales[$language])?self::$locales[$language]:null;
if (null === $locale) {
   require ...;
   self::$locales[$language] = $locale;
}

**Comment by bart-webleads** [comment]
Good point, it should store by language.

**Comment by WouterSioen** [comment]
I've changed to load by language.

**Comment by vytenizs** [comment]
if self::locales language wont exist, wont it throw a notice?

**Comment by WouterSioen** [comment]
Damn, It's not going well this monday :) I'll fix it

**Comment by WouterSioen** [comment]
Should be better now :)

**Comment by bart-webleads** [comment]
Passed tests.

Want the test code?

**Comment by WouterSioen** [comment]
It's not really needed, if you've tested it ;) I believe you :wink:

**Comment by bart-webleads** [comment]
ok

**Pull request merged**
